repos:
- hooks:
  - id: check-yaml
    stages:
    - commit
  - id: end-of-file-fixer
    stages:
    - commit
  - id: trailing-whitespace
    stages:
    - commit
  - id: check-json
    stages:
    - commit
  repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.3.0
- hooks:
  - id: black
    stages:
    - commit
    language_version: python3.9
  repo: https://github.com/psf/black
  rev: 21.4b2
- hooks:
  - id: nb-ensure-clean
    stages:
    - commit
  repo: https://gitlab.com/iamlikeme/nbhooks
  rev: 1.0.0
- hooks:
    - id: pylint
      stages:
      - commit
  repo: https://github.com/pycqa/pylint
  rev: pylint-2.6.0
